### ISSUE TITLE
undefined local variable or method `service_address' for Google::Cloud::Trace::V2:Module

### ISSUE THREAD

**Issue by thekevin-cisco** [census-instrumentation/ruby-stackdriver-exporter#23]
```
Unable to export to Stackdriver because: undefined local variable or method `service_address' for Google::Cloud::Trace::V2:Module
```

This appears to be broken since `0.33` of `google-cloud-trace`. Locking to `0.33` specifically resolves this issue. Something new was added to cause this.

https://github.com/googleapis/google-cloud-ruby/blob/5a2f46d026dd7b99baaa5920d99ce58d71d817a0/google-cloud-trace/lib/google/cloud/trace/v2.rb#L95-L111

**Comment by dazuma** [comment]
This was fixed in google-cloud-trace 0.38.1, released May 8.
