### ISSUE TITLE
The stackdriver exporter shouldn't issue a write request for an empty span list

### ISSUE THREAD

**Issue by bogdanap** [census-instrumentation/ruby-stackdriver-exporter#8]
While experimenting with Stackdriver Trace on a heavily used application, we've noticed that we were  always over the Stackdriver API write requests quota, regardless of the sampling strategy used (it also happens when using the NeverSample sampler).

This seems to be caused by the exporter issuing write requests even when the span list that it receives is empty (which happens, for example, when using the [RackMiddleware](https://github.com/census-instrumentation/opencensus-ruby/blob/f38628ec916bbdc1d3b634e076890a48933e1d61/lib/opencensus/trace/integrations/rack_middleware.rb#L86) integration and the [NeverSample](https://github.com/census-instrumentation/opencensus-ruby/blob/f38628ec916bbdc1d3b634e076890a48933e1d61/lib/opencensus/trace/samplers/never_sample.rb) sampler).

Considering this is a fairly small change that helps with the imposed requests quotas and should ease the load on the Stackdriver API, I think it would be worth adding.

**Comment by dazuma** [comment]
Fixed in gem version 0.1.1.
